### ISSUE TITLE
Want to use ballerina-style sequential diagram to visualize a go program

### ISSUE THREAD

**Issue by hitzhangjie** [ballerina-platform/plugin-vscode#129]
Hi, I really appreciate your work about the code visualization in sequential diagram.

I want to visualize my go code, I parsed the code and use AST to generate plantuml files, then use plantuml.jar to generate the picture.
- developer cannot interact with the static picture, like collapse, expand some code block;
- the picture maybe too big;
- plantuml picture looks not very user-friendly, like the "alt-else", "loop" representation.

I really like ballerina-style sequential diagram, it's fantastic. I want to use it to visualize my go diagram.

But I knows typescript a little, I want to know, if there's an easy way to quickly reuse it. I would be appreciated if you give me some suggestions.

Thanks.

**Comment by hevayo** [comment]
Hi @hitzhangjie 

The diagram library uses ballerina programs AST as the model to render the picture. So I do not see it is possible to reuse the diagram library to render Go code sine the Go AST and Ballerina AST is totally different. 

IMHO best approach would be to write a custom diagramming library for Go, May be you can reuse some components and design elements we have in the Ballerina diagram library. Btw Ballerina syntax is specifically designed around a sequence diagram ie. actions, works so if you render a Go program as a sequence diagram you would need to bring in additional set of constraints/standards.

**Comment by hitzhangjie** [comment]
@hevayo Thank you, I'll read the Ballerina diagram library to learn something.
