### ISSUE TITLE
Quick Run CodeLens for the Main Methods

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/plugin-vscode#150]
**Description:**
It would be super easy and improves UX if we can add a plugin initiated CodeLens to detect main methods and provide a shortcut to execute main method. This is already available in other IDEs such as IntelliJ.

**Comment by prabushi** [comment]
Reference: https://code.visualstudio.com/docs/java/java-debugging#_codelens

**Comment by hevayo** [comment]
We need to add this to running tests as well

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/12
