### ISSUE TITLE
Plugin fails with "unknown error" when the correct distribution is not set

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/plugin-vscode#176]
See the attached image. I forgot to set `BALLERINA_HOME` to the new distribution, which has the `ballerina -> bal` change. The error I received was "unknown error". It'd be good if we can give a specific error with details. For example, see the similar message I got for C# just above that message.
![Screenshot from 2021-01-25 11-40-16](https://user-images.githubusercontent.com/6260009/105668137-bbc8bb80-5f02-11eb-8e68-efe0076e03b0.png)

**Comment by prabushi** [comment]
Made the plugin work with both `bal` and `ballerina` commands with https://github.com/ballerina-platform/plugin-vscode/pull/193
