### ISSUE TITLE
Debug restart not working

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/plugin-vscode#180]
**Description:**
![debug_restart](https://user-images.githubusercontent.com/15815199/105688636-d8272100-5f1f-11eb-81b7-618a0ad251fc.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Swan Lake Alpha

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing since fixed with https://github.com/ballerina-platform/ballerina-lang/pull/28549
