### ISSUE TITLE
Syntax highlighting support Ballerina.toml, Deps.toml and K8.toml

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/plugin-vscode#190]
**Description:**
Now tooling and language server support language features for ballerina `.toml` files. Need syntax highlighting support for following ballerina project files;

- Ballerina.toml
- Dependencies.toml
- Kubernetes.toml

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hevayo** [comment]
Since these are toml file cant we just add the toml plugin for VSCode which will highlight them.

**Comment by rasika** [comment]
Didn't check how it appears with toml plugin. how about declaring toml plugin dependency for the plugin then?
