### ISSUE TITLE
Getting "Couldn't establish language server connection" when `allowExperimental` is enabled

### ISSUE THREAD

**Issue by dulajdilshan** [ballerina-platform/plugin-vscode#201]
**Description:**
$title

output of Ballerina log
```
[Info  - 2:19:11 PM] Connection to server got closed. Server will restart.
Couldn't establish language server connection.
ballerina: unknown option: '--experimental'
```

This happens when we have set 
```json
"ballerina.allowExperimental": true
```
with Swan Lake Alpha distribution.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rasika** [comment]
@dulajdilshan Is it for the latest SDK version or 1.2.x branch?

**Comment by prabushi** [comment]
> @dulajdilshan Is it for the latest SDK version or 1.2.x branch?

It was with the latest SL Alpha.
