### ISSUE TITLE
Can we make the auto-closing pairs intelligent

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/plugin-vscode#220]
**Description:**
$subject

**Comment by MaryamZi** [comment]
Observed the following on slalpha2.

Typing in < after i below adds <>.

```ballerina
public function main() {
    int i = 1;

    if i <cursor>
}
```

But when used in an XML literal where I expected this to happen, it did not.

**Comment by prabushi** [comment]
It seems the vscode [config](https://code.visualstudio.com/api/language-extensions/language-configuration-guide) only provides the capability to apply minimum conditional configurations (only has `notIn` string or comments per autoclosing pair, and `autoCloseBefore` config that applies for all pairs). Therefore, disabling the `<>` auto-closing pair for now.

**Comment by MaryamZi** [comment]
Can we also consider the single quote? The single quote is used in Ballerina with quoted identifiers. For example

```ballerina
public function main() {
    string 'int = "hello";
}
```

But this also adds the closing quote on slalpha2.

**Comment by prabushi** [comment]
> Can we also consider the single quote? The single quote is used in Ballerina with quoted identifiers. For example
> 
> ```ballerina
> public function main() {
>     string 'int = "hello";
> }
> ```
> 
> But this also adds the closing quote on slalpha2.

Yeah, removed the single quote too.
