### ISSUE TITLE
Closing angle bracket is always added

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/plugin-vscode#223]
**Description:**
$title.

**Affected Product Version:**
slalpha2 

**Steps to reproduce:**
Typing in `<` after `i` below adds `<>`. 
```ballerina
public function main() {
    int i = 1;

    if i <cursor>
}
```

Unless we're in an XML literal we don't need to add the closing angle bracket, right?

**Comment by prabushi** [comment]
Duplicate issue of https://github.com/ballerina-platform/plugin-vscode/issues/220
