### ISSUE TITLE
Syntax highlight issue 

### ISSUE THREAD

**Issue by yashodgayashan** [ballerina-platform/plugin-vscode#252]
**Description:**
There is a issue with syntax highlighting as when there are more than one return type all the return types will color in yellow except the first one which is blue. Color code should be blue.

**Steps to reproduce:**
`function getDatesFromDateRange(string startDate, string endDate, int monthVarience) returns [int|error, int|error, int|error, int|error] {
    log:printDebug("Start date is: " + startDate + ". End date is: " + endDate + ". Month varience is: " + monthVarience.toString());
    int|error startYear;
    int|error startMonth;
    int|error endYear;
    int|error endMonth;
    if (monthVarience == 0) {
        [startYear, startMonth] = extractYearAndMonthFromString(startDate);
    } else {
        time:Time|error tempTime = time:parse(startDate,"yyyy-MM-dd");
        if (tempTime is time:Time) {
            time:Time adjustedTime = time:subtractDuration(tempTime, 0, monthVarience, 0, 0, 0, 0, 0);
            string|error startPeriod = time:format(adjustedTime, "yyyy-MM-dd");
            if (startPeriod is string) {
                [startYear, startMonth] = extractYearAndMonthFromString(startPeriod);
            } else {
                return [stringTimeConversionError,
                        stringTimeConversionError,
                        stringTimeConversionError,
                        stringTimeConversionError];
            }
        } else {
            return [stringTimeConversionError,
                    stringTimeConversionError,
                    stringTimeConversionError,
                    stringTimeConversionError];
        }
    }
    [endYear, endMonth] = extractYearAndMonthFromString(endDate);
    log:printDebug("Start year is: " + startYear.toString() + ". Start month is: " + startMonth.toString());
    log:printDebug("End year is: " + endYear.toString() + ". End month is: " + endMonth.toString());
    return [startYear, startMonth, endYear, endMonth];
}`

**Affected Versions:**
Ballerina 1.0.1

**Suggested Labels (optional):**
Syntax Highlighting , Tooling 

**Suggested Assignees (optional):**
@Nadeeshaan,  @kaviththiranga

**Comment by prabushi** [comment]
Fixed with SL Alpha3 release.
