### ISSUE TITLE
Switch VSCode Plugin publishing automation from 1.2.x to swan lake

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/plugin-vscode#254]
**Description:**
Currently automated [vscode publishing action](https://github.com/ballerina-platform/ballerina-dev-website/blob/master/.github/workflows/publish_vscode_plugin.yml) is publishes 1.2.x release this needs to be switched swan lake releases

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/32
