### ISSUE TITLE
Enable command and debugger tests

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/plugin-vscode#256]
**Description:**
Enable CLI command and debugger tests disabled with https://github.com/ballerina-platform/plugin-vscode/pull/247/commits/65937522157cc66b797820a071443efbb15574a9

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hevayo** [comment]
Enable Windows test as well

**Comment by prabushi** [comment]
Enabled tests with https://github.com/ballerina-platform/plugin-vscode/pull/336/commits/b189553e91d7ecd8e2f2cd8a15a01c715fb6c87b and https://github.com/ballerina-platform/plugin-vscode/pull/336/commits/10896293f338a1c80e44bcfd8cb8e2387bd7ff6d

**Comment by prabushi** [comment]
Enabled tests on Windows with https://github.com/ballerina-platform/plugin-vscode/pull/337
