### ISSUE TITLE
Annotation declarations aren't highlighted propertly

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/plugin-vscode#264]
**Description:**
Consider the following annotation declaration.

![Screenshot from 2021-03-08 18-49-22](https://user-images.githubusercontent.com/11285165/110327165-a2597a00-803f-11eb-8711-52f0bc42c254.png)

Here, the name of the annotation is `configured` and it should be highlighted properly

**Comment by prabushi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-grammar/pull/79
