### ISSUE TITLE
Keywords after | are not highlighted 

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/plugin-vscode#267]
**Description:**
This is only observed when there are no preceding keywords (before |)

<img width="641" alt="Screenshot 2021-03-10 at 11 46 51" src="https://user-images.githubusercontent.com/5234623/110585744-325e0780-8197-11eb-9582-c43da6cb9ecf.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
```
class Person {
    string name;
    int age;
    function init(string name) {
        self.name = name;
    }
}

public function main() {
     Person|error p1 = new("John");
}
```

**Related Issues:**

**Comment by prabushi** [comment]
Tokenizer picks only when there's a preceding space.

**Comment by jclark** [comment]
I get a similar problem in slalpha4 with:

```
type CompareResult -1|0|1;
```

`CompareResult -1` is yellow and `|0|1` is blue.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/37
