### ISSUE TITLE
Readme's language feature resource navigates to an invalid page

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/plugin-vscode#286]
**Description:**
$title and it should navigate to https://ballerina.io/learn/tooling-guide/vs-code-extension/language-support/language-intelligence/ while the current link navigates to the installation guide

**Comment by praneesha** [comment]
Rathe than linking only to the Language Intelligence page, it should be useful to mention all the sections in the Docs and add the general link. Fixed this in https://github.com/ballerina-platform/plugin-vscode/pull/383.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/10
