### ISSUE TITLE
Wierd font size for ballerina code snippets when hover over a signature

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/plugin-vscode#300]
**Description:**
![Selection_212](https://user-images.githubusercontent.com/8381003/112112076-10bf4000-8bdb-11eb-97e0-c9897a89b9e9.png)

**Comment by KRVPerera** [comment]
Having the same issue. Not just font size I think code is not rendered at all as a code. Should not show starting and ending of the code block. 
>\`\`\` Ballerina code \`\`\`

**Comment by BuddhiWathsala** [comment]
I got the same. But when I cleared the Ballerina cache, it changes like this.
<img width="853" alt="Screenshot 2021-03-23 at 15 41 54" src="https://user-images.githubusercontent.com/18663444/112130445-81bc2300-8bee-11eb-88c0-74c95dfd0411.png">

**Comment by prabushi** [comment]
It seems this varies depending on the lib version picked up by ballerina.
<img width="852" alt="Screenshot 2021-03-23 at 15 38 56" src="https://user-images.githubusercontent.com/5234623/112131307-70bfe180-8bef-11eb-8060-59b4451a8ffb.png">
<img width="838" alt="Screenshot 2021-03-23 at 15 39 41" src="https://user-images.githubusercontent.com/5234623/112131348-7b7a7680-8bef-11eb-82dd-3eb0a4f194c6.png">

**Comment by prabushi** [comment]
This will be addressed in https://github.com/ballerina-platform/ballerina-lang/issues/29547
