### ISSUE TITLE
Wrong highlighting for returning streams with multiple types 

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/plugin-vscode#310]
**Description:**
The highlighting behavior is not consistent when we have streams with multiple types

![Screenshot from 2021-03-23 14-42-37 (copy)](https://user-images.githubusercontent.com/28644893/112123073-ed9a8d80-8be6-11eb-8611-6c8e2319663f.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
alpha3

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/41
