### ISSUE TITLE
Add 'Run with Choreo Observability' option

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/plugin-vscode#32]
**Description:**
Introduce **Run with Choreo Observability** option for the run command.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Need to introduce Choreo observability function for run on single bal file option when [this](https://github.com/wso2-enterprise/choreo/issues/1024) is fixed.

**Comment by prabushi** [comment]
Disabled in https://github.com/ballerina-platform/plugin-vscode/pull/111

**Comment by hevayo** [comment]
This can be achieved by adding compiler options in ballerina toml.
