### ISSUE TITLE
Formatter not found

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/plugin-vscode#321]
**Description:**
When trying to format a bal file, it gives formatter not found.
![Screenshot 2021-03-23 185738](https://user-images.githubusercontent.com/4398820/112154112-f5b7f480-8c09-11eb-87d6-868d00e7b780.png)

This may have been cause by https://github.com/ballerina-platform/plugin-vscode/issues/322

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
SL Alpha3

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**
Shift+Alt+F

**Related Issues:**

**Comment by prabushi** [comment]
Suppose this is using the 1.2.13 extension as mentioned in https://github.com/ballerina-platform/plugin-vscode/issues/322. Could you please try with the latest?

**Comment by prabushi** [comment]
Please reopen if you still get the above mentioned error with the SL vscode extension.
