### ISSUE TITLE
Windows not picking up the distribution location

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/plugin-vscode#322]
**Description:**
Following log is printed:
```
Ballerina home is configured in settings.
Plugin version: 1.2.13
Ballerina version: 'C:\Program' is not recognized as an internal or external command,
Failed to activate Ballerina extension. Error when checking ballerina version. Cannot read property 'map' of null
```

**Steps to reproduce:**
![Screenshot 2021-03-23 184346](https://user-images.githubusercontent.com/4398820/112156050-e76ad800-8c0b-11eb-98e3-152575b80d3d.png)
![Screenshot 2021-03-23 184307](https://user-images.githubusercontent.com/4398820/112156056-e89c0500-8c0b-11eb-9870-c4947ea80d73.png)

If I don't set the ballerina distribution. I get the following.
![Screenshot 2021-03-23 191744](https://user-images.githubusercontent.com/4398820/112156827-9effea00-8c0c-11eb-81be-3fb4bfcb2f3f.png)

But as you can see in the terminal/cmd, `bal home` works.
**Affected Versions:**
SL Alpha3

**OS, DB, other environment details and versions:**
Windows 10

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
Ballerina plugin 2.1.13 is not compatible with SL Alpha3 runtime. Please use the vsix from the respective [release](https://github.com/ballerina-platform/plugin-vscode/releases/tag/vswan-lake-alpha3).

**Comment by prabushi** [comment]
Please reopen if you still get the above mentioned error with the SL vscode extension.
