### ISSUE TITLE
Cannot Debug Ballerina App in VSCode

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/plugin-vscode#344]
**Description:**
When try to debug a simple Ballerina service I get the following output on the OUTPUT tab of the VSCode.

```
start Thu Apr 01 2021 17:54:59 GMT+0530 (India Standard Time)
Rejected bal: Thu Apr 01 2021 17:55:09 GMT+0530 (India Standard Time)
Error: Command failed: bal version
/bin/sh: 1: bal: not found
Rejected ballerina: Thu Apr 01 2021 17:55:09 GMT+0530 (India Standard Time)
Error: Command failed: ballerina version
/bin/sh: 1: ballerina: not found
final1: Thu Apr 01 2021 17:55:09 GMT+0530 (India Standard Time)
Failed to activate Ballerina extension. Error when checking ballerina version. AggregateError: All promises were rejected
```
![Screenshot from 2021-04-01 18-00-54](https://user-images.githubusercontent.com/1388997/113294167-4919f900-9314-11eb-8ca6-c00d56ec526b.png)

**Affected Product Version:**
Ballerina Swan Lake (SL) Alpha 3

**OS, DB, other environment details and versions:**    
Ubuntu 18.04, VSCode 1.53.2, Ballerina VSCode plugin for SL ALpha 3 (i.e., ballerina-swan-lake-alpha3.vsix)

**Steps to reproduce:**
- Install the `ballerina-swan-lake-alpha3.vsix`
- Try to debug the app shown in the above image (or any other similar Ballerina app)

**Related Issues:**
N/A

**Comment by prabushi** [comment]
This was due to some caching issue in Java. Need to add debug logs to capture failing scenarios along with the failure reason.
