### ISSUE TITLE
Syntax highlighting seems incorrect for module level function variables/anonymous functions

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/plugin-vscode#367]
**Description:**
$title.

Note the variable name, parameter name and returns keyword.

![anon_func_highlighting](https://user-images.githubusercontent.com/8376983/64474337-74b51b80-d191-11e9-9ae9-fb926fb17101.png)

**Steps to reproduce:**
```ballerina
function(int i) returns string bar = function (int i) returns string {
    return "bar";
};

public function main() {
    function(int i) returns string bar = function (int i) returns string {
        return "bar";
    };
}
```

**Affected Versions:**
```cmd
$ ballerina -v
Ballerina 1.0.0-rc1-SNAPSHOT
Language specification 2019R3
Ballerina tool 1.0.0
```

**Comment by prabushi** [comment]
<img width="569" alt="Screenshot 2021-04-22 at 18 18 01" src="https://user-images.githubusercontent.com/5234623/115716800-320c7b00-a397-11eb-8729-5216de714c77.png">
Highlighting is consistent now. But, have to fix the incorrect highlighting of the variable name.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/22
