### ISSUE TITLE
Change the Label of the Ballerina Doc command

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/plugin-vscode#385]
**Description:**
In the current implementation, the label of the Ballerina doc command in VSCode shows as `Ballerina: Document` which is confusing. What if we have a label which is bit more descriptive.

Suggestion: `Document the Package` which is tallied with the ballerina cli manual's description

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/49
