### ISSUE TITLE
Change error message when the Ballerina Examples are not found in the distribution

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/plugin-vscode#386]
**Description:**
In the current implementation, when the examples cannot be found in the picked ballerina home, the following error is shown,

<img width="892" alt="Screenshot 2021-05-04 at 12 15 26" src="https://user-images.githubusercontent.com/1329674/116968725-abc73180-acd2-11eb-8e20-161f32cf6f2b.png">

We can replace the [BALLERINA_HOME] part with the actual URI

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/50
