### ISSUE TITLE
Cannot escape from add module command's input area

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/plugin-vscode#387]
**Description:**
Consider the following screen capture. When there is no input in the text area, hitting the `esc` will not close the command input area.

https://user-images.githubusercontent.com/1329674/116986076-fbb1f280-acea-11eb-8945-b4a61d4eab3c.mp4

**Steps to reproduce:**
Execute the add module command. Without entering a module name, hit `esc`

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/51
