### ISSUE TITLE
New Diagram is not working in Windows

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/plugin-vscode#391]
This issue is observed in SL-beta.1.RC1 for the Following program.

```ballerina
import ballerina/http;
service / on new http:Listener(8080) {
    resource function get getResource(http:Caller caller, http:Request req) returns error?{
        _ = check caller->respond("Hello world...!!!");
    }
}
```

![SimpleValues-1620357997576](https://user-images.githubusercontent.com/1356214/117393693-4d889180-af12-11eb-8c0f-d7dc59d8e2ce.gif)

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/53
