### ISSUE TITLE
RC5 shows "Ballerina SDK: Detecting" forever

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/plugin-vscode#398]
In Beta1 RC5 on Windows, VS Code shows "Ballerina SDK: Detecting" forever
<img width="926" alt="Screenshot 2021-05-27 153816" src="https://user-images.githubusercontent.com/499966/119794564-d5eec680-bf01-11eb-9b28-6abadd7d1524.png">

**Comment by prabushi** [comment]
@jclark Could you please check if you have another Ballerina extension installed in your VS Code? If so, uninstall the Ballerina extension that comes under `ballerina.ballerina` organization and keep the one that comes under wso2.ballerina. Apparently, the older version has picked up first.

<img width="866" alt="Screenshot 2021-05-28 at 13 34 44" src="https://user-images.githubusercontent.com/5234623/119951631-c7fc7c80-bfb9-11eb-97fa-9d01ee3cefda.png">

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/78
