### ISSUE TITLE
Pasting some string within double quotes should escape the pasted string

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/plugin-vscode#402]
**Description:**
We as programmers usually expect the IDE to escape the text we paste within double quotes.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/95
