### ISSUE TITLE
Improve test coverage of VSCode extension

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/plugin-vscode#44]
We have some several tests covering logic of detecting Ballerina distribution and spawning lang server up. But we have to improve the tests to capture other features.
For example: 

- [ ] Diagram rendering and editing
- [ ] Documentation preview
- [ ] API designer
- [ ] Network logs

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/6
