### ISSUE TITLE
Debugging support for diagram

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/plugin-vscode#46]
While debugging a ballerina program, in source-diagram split view, highlight current statement in diagram.

This will be simply a way of showing where current executing statement is in the program flow, in the sequence diagram. We will not support setting debug points or evaluating variables, etc. within graphical view.

**Comment by prabushi** [comment]
We've discontinued the diagram support in 1.2.x, and a new diagram will be introduced to the Swan Lake plugin.
