### ISSUE TITLE
Do not show "Ballerina project overview" for non-project directories

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/plugin-vscode#56]
**Description:**
Ballerina VSCode plugin shows the "Ballerina project overview" section, even if I open a single bal file or a directory of just bal files.  IMO, we should even display the tab in this case.

**Affected Versions:**
1.0.0-RC1

**Comment by prabushi** [comment]
Removed the project overview https://github.com/ballerina-platform/plugin-vscode/issues/123.

**Comment by prabushi** [comment]
We'll be introducing the project overview again.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/20
