### ISSUE TITLE
Completions don't group related constructs together

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/plugin-vscode#57]
@pubudu91 commented on [Mon Sep 21 2020](https://github.com/ballerina-platform/ballerina-lang/issues/25975)

See the following:
![Peek 2020-09-21 15-43](https://user-images.githubusercontent.com/6260009/93755726-65c8cc00-fc21-11ea-94aa-3e46e0986128.gif)

In the above case, `a` and `b` are grouped together while to find `c`, you have to scroll down.

**Comment by nadeeshaan** [comment]
This has been addressed with https://github.com/ballerina-platform/ballerina-lang/pull/28349. Hence closing the issue
