### ISSUE TITLE
Need to fix the VSCode warning msg which mentions ballerina.home setting

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/plugin-vscode#58]
This setting was only intended to be used by VSCode plugin developers (along with the setting enable.dev.mode).

But, if the user is using the ZIP distribution, they only have the option of manually setting ballerina.home. In this case, it is not user friendly to ask them to set another setting to make ballerina.home effective.

VSCode should be able to auto detect Ballerina home for all other cases. We should only ask users to restart the editor to get it working - if they used the installer to install Ballerina. 

We may need to provide an alternate setting and a warning msg which is not confusing for users.

**Comment by prabushi** [comment]
Will be fixed with https://github.com/ballerina-platform/plugin-vscode/issues/62
