### ISSUE TITLE
[VS Code Plugin] - Fails to start

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [ballerina-platform/plugin-vscode#59]
**Description:**

The Ballerina VS Code plugin fails to start when loading VS Code, giving the following errors:

 
![image](https://user-images.githubusercontent.com/32578617/78212416-47351400-74cd-11ea-88d2-b6c5dd409317.png)

**Steps to reproduce:**

**Affected Versions:**
1.2.0

**OS, DB, other environment details and versions:**
Ubuntu 18.04.3 LTS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
The mentioned is related to an issue with installing the Ballerina distribution. Hence, the VSCode plugin isn't configured properly. We hope the Ballerina installation works fine now. Please reopen the issue if you still face the issue.
