### ISSUE TITLE
Ballerina: Home config is read only when plugin development mode is enabled

### ISSUE THREAD

**Issue by a5anka** [ballerina-platform/plugin-vscode#62]
## Description

Users of the VS Code plugin have to enable "plugin development mode" if they want to change Ballerina home. This is a bit counter-intuitive. Therefore what if we honor the ballerina home config irrespective of whether the user has enabled "plugin development mode" or not.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/25
