### ISSUE TITLE
Object doc is not shown for object that does not have method docs

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/plugin-vscode#68]
**Description:**
$subject 

Before adding method doc
![Screen Shot 2019-09-07 at 12 07 31 PM](https://user-images.githubusercontent.com/1496990/64470964-ef1d7580-d168-11e9-8704-7fb73f8b83a0.png)

After adding method doc
![Screen Shot 2019-09-07 at 12 08 25 PM](https://user-images.githubusercontent.com/1496990/64470966-ef1d7580-d168-11e9-8e07-0da030a4cf63.png)

If the object contain multiple methods and at least one method does not have a doc comment, documentation does not shown for the entire object type.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
Removed the Doc preview https://github.com/ballerina-platform/plugin-vscode/issues/124
