### ISSUE TITLE
Consider collapsing a [resource] function & its annotations/docs together

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/plugin-vscode#70]
When collapsing a resource function, I have to manually collapse the annotations after collapsing the function. Since docs / annots / code go together, can we make collapse just fold all of it at once?

**Comment by prabushi** [comment]
Language Server [FoldingRange](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_foldingRange) capability supports specifying a set of ranges to fold. If we fold docs and code together, we can make only a part of the doc(only the top part) visible, making it hard to identify the underline capability of code without its declaration.
IDEs like IDEA, VSCode support folding docs, imports, and any other similar indented code parts, separately. 
Shall we follow a similar approach?

![test](https://user-images.githubusercontent.com/5234623/99501907-68863a00-29a2-11eb-8a7b-e7d897f3ddee.jpg)
