### ISSUE TITLE
VS Code: syntax highlighting not working for "key" keyword

### ISSUE THREAD

**Issue by DeveloperLK** [ballerina-platform/plugin-vscode#71]
**Description:**

"key" keyword in ballerina v1.0.0 does not highlight in the VS Code editor. ("primarykey" keyword in ballerina v0.982.0 gets highlighted).

**Steps to reproduce:**
` table<Employee> tbEmployee = table {
        { key id, name, salary },
        [ { 1, "Mary",  300.5 },
          { 2, "John",  200.5 },
          { 3, "Jim", 330.5 }
        ]
    };`

**Affected Versions:**
Ballerina v1.0.1

**OS, DB, other environment details and versions:**
Ubuntu 18.04(Linux)

**Comment by prabushi** [comment]
This is fixed in the Swan Lake Alpa plugin.

<img width="1016" alt="Screenshot 2021-02-11 at 16 54 23" src="https://user-images.githubusercontent.com/5234623/107630729-fc0d9500-6c89-11eb-9e86-e38d631eb29d.png">
