### ISSUE TITLE
VS Code: syntax highlighting not working for "source" keyword 

### ISSUE THREAD

**Issue by DeveloperLK** [ballerina-platform/plugin-vscode#72]
**Description:**
"source" keyword in ballerina v1.0.0 does not highlight in the VS Code editor. 
_error: invalid token 'source'_

**Steps to reproduce:**
```
import ballerina/io;

public function main() {
    string source = "Hello World!";
    io:println(source);
}
```
**Affected Versions:**
Ballerina v1.0.3

**OS, DB, other environment details and versions:**
Ubuntu 18.04(Linux)

**Comment by prabushi** [comment]
Highlighting is fixed in the latest (SL Alpha2).

<img width="434" alt="Screenshot 2021-02-17 at 17 58 11" src="https://user-images.githubusercontent.com/5234623/108204468-daa91f00-7149-11eb-9c2f-8dc77954f8f9.png">
