### ISSUE TITLE
Better have a different colour  for "TODO" statements in VSCode Ballerina extension plugin

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/plugin-vscode#74]
**Description:**

Please see below. 
Better have a different colour be default for TODO statements so they are visually draw the attention of the coder. 

<img width="488" alt="Screen Shot 2019-06-30 at 6 53 36 PM" src="https://user-images.githubusercontent.com/4967046/60397297-0e949280-9b69-11e9-9c4a-d3948fd72a90.png">

**Steps to reproduce:**

N/A

**Affected Versions:**

Plugin version: 0.991.2
Ballerina version: 0.991.0

**Comment by prabushi** [comment]
Closing as the TODO highlighting works for .bal files using available extensions.

**Comment by hevayo** [comment]
We will not implement this given the todo plugin.
