### ISSUE TITLE
Add instructions to add ballerina executable to path - for zip users

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/plugin-vscode#80]
To avoid problems with VSCode extension trying to auto detect the distribution path or user trying to configure ballerina.home setting,

We should ask all zip users to create an link in ```/usr/local/bin (on unix)``` or add Ballerina executable to PATH somehow.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/24
