### ISSUE TITLE
the File overview of hello.bal in vscode is blank 

### ISSUE THREAD

**Issue by starsmall-xiaoqq** [ballerina-platform/plugin-vscode#82]
**Description:**

1. Create the  hello.bal.
import ballerina/io;
public function main() {
    io:println("Hello World!");
}

2. click File Overview icon

the overview window is blank (white background).

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
windows 10, vscode 1.46.1
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
We've discontinued the diagram support in 1.2.x, and a new diagram will be introduced to the Swan Lake plugin.
