### ISSUE TITLE
Eclipse Che and Theia integration

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/plugin-vscode#85]
### Theia
- [x] Make VSCode extension run on Theia 

See demo: 
https://drive.google.com/file/d/1czjrEkCxN1ZrqOo5p6OITZ4wJVJeE9KK/view?usp=sharing

#### Raised issues so far
- https://github.com/theia-ide/theia/issues/4267 (Found a fix but not the proper fix)
- https://github.com/theia-ide/theia/issues/4251 ([Sent a PR with the fix](https://github.com/theia-ide/theia/pull/4255))
- https://github.com/theia-ide/theia/issues/3921 (resolved)
- https://github.com/theia-ide/theia/issues/3844 (resolved)

#### what's next

- [ ] Get running and debugging working

- [ ] Make doc preview, diagram & api designer appear side by side with code (https://github.com/theia-ide/theia/issues/4322)

### Che
- [ ] Go through Che 7 changes / release plan
- [ ] Ballerina Stacks
- [ ] Installers
- [ ] Factories
- [ ] Che extension for LS

**Comment by hevayo** [comment]
differed
