### ISSUE TITLE
Non-keywords highlighted as keywords within record/object type descriptors

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/plugin-vscode#90]
![Screenshot from 2019-12-10 10-23-01](https://user-images.githubusercontent.com/6260009/70496921-6df2c780-1b37-11ea-8d94-b30c259b44d1.png)
Note that `country` is a non-existent type and not a keyword.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/ballerina-plugin-vscode/issues/23
