### ISSUE TITLE
Even if I stops the debugging session, vs code continues to run ballerina process in background

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/plugin-vscode#94]
**Description:**
I debugged a ballerina service and stopped it. and when I starts debugging vscode complains that (debug) port is already taken. What has happened is VScode didn't stop/terminate ballerina program previously therefore, I can't start the new sessions.
This is a real irritation.

**Suggested Labels:**
blocker
**Suggested Assignees:**

**Affected Product Version:**
ballerina 1.2.9,
**OS, DB, other environment details and versions:**    
Mac OS
**Steps to reproduce:**
see above

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing since this is fixed with #https://github.com/ballerina-platform/ballerina-lang/pull/28549
